### ISSUE TITLE
Plugins remain intact to canvas even after disabling it from settings.

### ISSUE THREAD

**Issue by utsavatwork** [Abdulmumin1/DevCanvas#256]
Below screenshot shows, how "font-bold p-1" (tailwind) class still gets applied to html element even when tailwind plugin is unchecked in the settings.

> Note that after initial page loading, tailwind is disabled as it should be. But after you enable it first, then the mentioned bug occurs.

![Screenshot from 2024-10-15 01-15-08](https://github.com/user-attachments/assets/62d1f08c-8cf4-4eb3-b65c-4cb02f45246f)

**Comment by Abdulmumin1** [comment]
Thanks for this @utsavatwork! would be working to get it fixed in a few days.
